from functionsTest import create_db, create_table, print_graph, open_db, table_add_tri, table_del_tri_one
from functionsTest import table_del_tri_list,sparqlCommonObj, autopull
from paths import DEFAULT_LOADSTAR_URI,DEFAULT_DATABASE_PATH, DATABASE_FOLDER, TEST_DATABASE_PATH
from paths import DEFAULT_LOADSTAR_USERNAME, DEFAULT_LOADSTAR_TABLENAME, DEFAULT_LOADSTAR_SUBJECT, DEFAULT_LOADSTAR_SUBJECT2
from paths import test_doubles, test_doubles2, default_double
import logging
logging.basicConfig()
from metadataFuncs import autoform_metadata, print_metadata
import Tkinter as tk

#create_db()

#create_table(DEFAULT_LOADSTAR_USERNAME,DEFAULT_LOADSTAR_TABLENAME,DEFAULT_LOADSTAR_SUBJECT,test_doubles)

#print_graph(DEFAULT_DATABASE_PATH,DEFAULT_LOADSTAR_USERNAME, DEFAULT_LOADSTAR_TABLENAME)

#table_add_tri(DEFAULT_LOADSTAR_USERNAME,DEFAULT_LOADSTAR_TABLENAME,DEFAULT_LOADSTAR_SUBJECT,test_doubles2)

#print_graph(DEFAULT_DATABASE_PATH,DEFAULT_LOADSTAR_USERNAME, DEFAULT_LOADSTAR_TABLENAME)

#table_del_tri_one(DEFAULT_LOADSTAR_USERNAME, DEFAULT_LOADSTAR_TABLENAME, DEFAULT_LOADSTAR_SUBJECT, default_double)

#print_graph(DEFAULT_DATABASE_PATH,DEFAULT_LOADSTAR_USERNAME, DEFAULT_LOADSTAR_TABLENAME)

#table_del_tri_list(DEFAULT_LOADSTAR_USERNAME,DEFAULT_LOADSTAR_TABLENAME,DEFAULT_LOADSTAR_SUBJECT,test_doubles2)

#print_graph(DEFAULT_DATABASE_PATH,DEFAULT_LOADSTAR_USERNAME, DEFAULT_LOADSTAR_TABLENAME)

#autoform_metadata()

#print_metadata()

#autopull(DEFAULT_LOADSTAR_USERNAME,'Physics',DEFAULT_LOADSTAR_SUBJECT2,database_path=DEFAULT_DATABASE_PATH)
#autopull(DEFAULT_LOADSTAR_USERNAME,'Mathematics',DEFAULT_LOADSTAR_SUBJECT,database_path=DEFAULT_DATABASE_PATH)
#sparqlCommonObj(DEFAULT_LOADSTAR_USERNAME,DEFAULT_LOADSTAR_USERNAME,DEFAULT_LOADSTAR_TABLENAME,'Physics')